import {
    Cpu,
    Briefcase,
    Palette,
    Stethoscope,
    School,
    BookMarked,
    Lightbulb,
    Globe,
    Target,
} from "lucide-react";

export const programs = [
    {
        id: 1,
        icon: <Cpu className="w-8 h-8" />,
        title: "Engineering & Technology",
        category: "STEM Programs",
        description:
            "Cutting-edge programs in computer science, engineering, and emerging technologies. Our comprehensive curriculum combines theoretical knowledge with hands-on experience, preparing students for the rapidly evolving tech industry. From artificial intelligence to sustainable engineering solutions, our programs are designed to tackle tomorrow's challenges.",
        shortDescription:
            "Cutting-edge programs in computer science, engineering, and emerging technologies",
        courses: "45+ Programs",
        color: "from-primary to-primary-dark",
        image: "/images/landing/engineering.svg",
        duration: "4 Years",
        students: "1,200+",
        degree: "Bachelor/Master",
        mode: "On Campus & Online",
        curriculum: [
            "Advanced Programming & Software Development",
            "Data Structures & Algorithms",
            "Machine Learning & AI",
            "Cybersecurity & Network Systems",
            "Database Management Systems",
            "Web & Mobile Development",
            "Cloud Computing & DevOps",
            "Engineering Mathematics",
        ],
        careers: [
            "Software Engineer",
            "Data Scientist",
            "AI/ML Engineer",
            "Cybersecurity Analyst",
            "DevOps Engineer",
            "Full Stack Developer",
            "System Architect",
            "Product Manager",
        ],
        requirements: [
            "High school diploma with mathematics and science subjects",
            "Minimum GPA of 3.0 or equivalent",
            "SAT/ACT scores (recommended)",
            "Personal statement or essay",
            "Letter of recommendation from mathematics or science teacher",
        ],
    },
    {
        id: 2,
        icon: <Briefcase className="w-8 h-8" />,
        title: "Business & Management",
        category: "Business Programs",
        description:
            "Comprehensive business education with real-world application and industry partnerships. Our programs integrate modern business practices with ethical leadership principles, preparing graduates to excel in the global marketplace. Students gain expertise in strategic thinking, financial analysis, and innovative problem-solving.",
        shortDescription:
            "Comprehensive business education with real-world application and industry partnerships",
        courses: "30+ Programs",
        color: "from-accent-dark to-accent",
        image: "/images/landing/business.svg",
        duration: "4 Years",
        students: "950+",
        degree: "Bachelor/MBA",
        mode: "On Campus & Hybrid",
        curriculum: [
            "Strategic Management & Leadership",
            "Financial Analysis & Accounting",
            "Marketing & Brand Management",
            "Operations & Supply Chain",
            "Business Analytics & Intelligence",
            "Entrepreneurship & Innovation",
            "International Business",
            "Business Ethics & Sustainability",
        ],
        careers: [
            "Business Analyst",
            "Marketing Manager",
            "Financial Consultant",
            "Operations Manager",
            "Management Consultant",
            "Project Manager",
            "Investment Banker",
            "Entrepreneur",
        ],
        requirements: [
            "High school diploma with strong academic record",
            "Minimum GPA of 2.8 or equivalent",
            "English proficiency test scores",
            "Personal statement highlighting leadership experience",
            "Resume showcasing extracurricular activities",
        ],
    },
    {
        id: 3,
        icon: <Palette className="w-8 h-8" />,
        title: "Arts & Sciences",
        category: "Liberal Arts",
        description:
            "Liberal arts education fostering critical thinking and creative problem-solving. Our interdisciplinary approach encourages students to explore diverse fields of knowledge while developing strong analytical and communication skills. From literature and philosophy to natural sciences, students gain a well-rounded foundation for lifelong learning.",
        shortDescription:
            "Liberal arts education fostering critical thinking and creative problem-solving",
        courses: "25+ Programs",
        color: "from-primary-dark to-accent-dark",
        image: "/images/landing/arts.svg",
        duration: "4 Years",
        students: "750+",
        degree: "Bachelor/Master",
        mode: "On Campus",
        curriculum: [
            "Critical Thinking & Philosophy",
            "Literature & Creative Writing",
            "History & Cultural Studies",
            "Natural Sciences & Research Methods",
            "Foreign Languages & Linguistics",
            "Art History & Visual Arts",
            "Psychology & Social Sciences",
            "Mathematics & Statistics",
        ],
        careers: [
            "Research Analyst",
            "Content Creator",
            "Museum Curator",
            "Social Worker",
            "Journalist",
            "Teacher/Professor",
            "Policy Analyst",
            "Cultural Consultant",
        ],
        requirements: [
            "High school diploma with diverse academic subjects",
            "Minimum GPA of 2.5 or equivalent",
            "Writing sample or portfolio",
            "Personal essay demonstrating intellectual curiosity",
            "Interview with academic advisor",
        ],
    },
    {
        id: 4,
        icon: <Stethoscope className="w-8 h-8" />,
        title: "Health Sciences",
        category: "Medical Programs",
        description:
            "Preparing the next generation of healthcare professionals and researchers. Our programs combine rigorous scientific training with compassionate patient care, utilizing state-of-the-art simulation labs and clinical partnerships. Students develop both technical expertise and the interpersonal skills essential for healthcare excellence.",
        shortDescription:
            "Preparing the next generation of healthcare professionals and researchers",
        courses: "20+ Programs",
        color: "from-accent to-accent-light",
        image: "/images/landing/health.svg",
        duration: "4-6 Years",
        students: "600+",
        degree: "Bachelor/Master/Doctorate",
        mode: "On Campus & Clinical",
        curriculum: [
            "Human Anatomy & Physiology",
            "Medical Terminology & Ethics",
            "Pharmacology & Drug Interactions",
            "Clinical Assessment & Diagnosis",
            "Patient Care & Communication",
            "Medical Research Methods",
            "Healthcare Technology Systems",
            "Public Health & Epidemiology",
        ],
        careers: [
            "Registered Nurse",
            "Physical Therapist",
            "Medical Technologist",
            "Healthcare Administrator",
            "Clinical Researcher",
            "Pharmacist",
            "Radiologic Technologist",
            "Health Educator",
        ],
        requirements: [
            "High school diploma with strong science and mathematics background",
            "Minimum GPA of 3.2 or equivalent",
            "Prerequisite courses in biology, chemistry, and physics",
            "Healthcare experience or volunteer work preferred",
            "Background check and immunization records",
        ],
    },
    {
        id: 5,
        icon: <School className="w-8 h-8" />,
        title: "Education",
        category: "Teaching Programs",
        description:
            "Innovative teacher preparation and educational leadership programs. Our education programs emphasize modern pedagogical approaches, inclusive teaching strategies, and technology integration. Students learn to inspire and educate diverse learners while developing skills in curriculum design and educational assessment.",
        shortDescription:
            "Innovative teacher preparation and educational leadership programs",
        courses: "15+ Programs",
        color: "from-primary to-accent",
        image: "/images/landing/education.svg",
        duration: "4 Years",
        students: "400+",
        degree: "Bachelor/Master",
        mode: "On Campus & Field Experience",
        curriculum: [
            "Educational Psychology & Development",
            "Curriculum Design & Assessment",
            "Classroom Management Strategies",
            "Inclusive Education & Special Needs",
            "Educational Technology Integration",
            "Teaching Methods & Pedagogy",
            "Educational Research & Data Analysis",
            "School Leadership & Administration",
        ],
        careers: [
            "Elementary Teacher",
            "Secondary Teacher",
            "Special Education Teacher",
            "School Counselor",
            "Educational Administrator",
            "Curriculum Specialist",
            "Educational Technology Coordinator",
            "Training & Development Specialist",
        ],
        requirements: [
            "High school diploma with strong academic performance",
            "Minimum GPA of 2.75 or equivalent",
            "Communication and interpersonal skills assessment",
            "Field experience or volunteer work with children/youth",
            "Background check and fingerprinting required",
        ],
    },
    {
        id: 6,
        icon: <BookMarked className="w-8 h-8" />,
        title: "Graduate Studies",
        category: "Advanced Programs",
        description:
            "Advanced degrees and research opportunities across all disciplines. Our graduate programs offer specialized knowledge and research experience under the mentorship of distinguished faculty. Students engage in cutting-edge research while developing expertise that advances their fields and prepares them for leadership roles.",
        shortDescription:
            "Advanced degrees and research opportunities across all disciplines",
        courses: "60+ Programs",
        color: "from-accent-dark to-primary",
        image: "/images/landing/graduate.svg",
        duration: "2-7 Years",
        students: "800+",
        degree: "Master/Doctorate",
        mode: "On Campus & Research",
        curriculum: [
            "Advanced Research Methodologies",
            "Specialized Subject Matter Expertise",
            "Statistical Analysis & Data Interpretation",
            "Academic Writing & Publication",
            "Grant Writing & Funding Acquisition",
            "Conference Presentation Skills",
            "Interdisciplinary Collaboration",
            "Ethics in Research & Practice",
        ],
        careers: [
            "Research Scientist",
            "University Professor",
            "Industry Specialist",
            "Policy Researcher",
            "Consultant",
            "R&D Manager",
            "Think Tank Analyst",
            "Academic Administrator",
        ],
        requirements: [
            "Bachelor's degree from accredited institution",
            "Minimum GPA of 3.0 in undergraduate studies",
            "GRE/GMAT scores (program dependent)",
            "Statement of purpose and research interests",
            "Three letters of recommendation from academic or professional references",
            "Research experience or relevant work experience preferred",
        ],
    },
];

export const features = [
    {
        icon: <Lightbulb className="w-8 h-8" />,
        title: "Innovation Hub",
        description:
            "State-of-the-art research facilities and startup incubators fostering breakthrough discoveries",
        color: "from-accent-light to-accent",
    },
    {
        icon: <Globe className="w-8 h-8" />,
        title: "Global Partnerships",
        description:
            "Collaborations with leading universities and institutions worldwide for impactful research",
        color: "from-primary to-primary-dark",
    },
    {
        icon: <Target className="w-8 h-8" />,
        title: "Career Success",
        description:
            "Comprehensive career services and industry connections ensuring graduate success",
        color: "from-accent-dark to-primary",
    },
];
