import {
    Cpu,
    Briefcase,
    Palette,
    Stethoscope,
    School,
    BookMarked,
    Lightbulb,
    Globe,
    Target,
    Users,
    Mic,
    Wine,
    Library,
    HeartPulse,
} from "lucide-react";

export const stats = [
    { number: "25,000+", label: "Students" },
    { number: "200+", label: "Programs" },
    { number: "95%", label: "Job Placement" },
];

export const programs = [
    {
        id: 1,
        icon: <Cpu className="w-8 h-8" />,
        title: "Engineering & Technology",
        category: "STEM Programs",
        description:
            "Cutting-edge programs in computer science, engineering, and emerging technologies. Our comprehensive curriculum combines theoretical knowledge with hands-on experience, preparing students for the rapidly evolving tech industry. From artificial intelligence to sustainable engineering solutions, our programs are designed to tackle tomorrow's challenges.",
        shortDescription:
            "Cutting-edge programs in computer science, engineering, and emerging technologies",
        courses: "45+ Programs",
        color: "from-primary to-primary-dark",
        image: "/images/landing/engineering.svg",
        duration: "4 Years",
        students: "1,200+",
        degree: "Bachelor/Master",
        mode: "On Campus & Online",
        curriculum: [
            "Advanced Programming & Software Development",
            "Data Structures & Algorithms",
            "Machine Learning & AI",
            "Cybersecurity & Network Systems",
            "Database Management Systems",
            "Web & Mobile Development",
            "Cloud Computing & DevOps",
            "Engineering Mathematics",
        ],
        careers: [
            "Software Engineer",
            "Data Scientist",
            "AI/ML Engineer",
            "Cybersecurity Analyst",
            "DevOps Engineer",
            "Full Stack Developer",
            "System Architect",
            "Product Manager",
        ],
        requirements: [
            "High school diploma with mathematics and science subjects",
            "Minimum GPA of 3.0 or equivalent",
            "SAT/ACT scores (recommended)",
            "Personal statement or essay",
            "Letter of recommendation from mathematics or science teacher",
        ],
    },
    {
        id: 2,
        icon: <Briefcase className="w-8 h-8" />,
        title: "Business & Management",
        category: "Business Programs",
        description:
            "Comprehensive business education with real-world application and industry partnerships. Our programs integrate modern business practices with ethical leadership principles, preparing graduates to excel in the global marketplace. Students gain expertise in strategic thinking, financial analysis, and innovative problem-solving.",
        shortDescription:
            "Comprehensive business education with real-world application and industry partnerships",
        courses: "30+ Programs",
        color: "from-accent-dark to-accent",
        image: "/images/landing/business.svg",
        duration: "4 Years",
        students: "950+",
        degree: "Bachelor/MBA",
        mode: "On Campus & Hybrid",
        curriculum: [
            "Strategic Management & Leadership",
            "Financial Analysis & Accounting",
            "Marketing & Brand Management",
            "Operations & Supply Chain",
            "Business Analytics & Intelligence",
            "Entrepreneurship & Innovation",
            "International Business",
            "Business Ethics & Sustainability",
        ],
        careers: [
            "Business Analyst",
            "Marketing Manager",
            "Financial Consultant",
            "Operations Manager",
            "Management Consultant",
            "Project Manager",
            "Investment Banker",
            "Entrepreneur",
        ],
        requirements: [
            "High school diploma with strong academic record",
            "Minimum GPA of 2.8 or equivalent",
            "English proficiency test scores",
            "Personal statement highlighting leadership experience",
            "Resume showcasing extracurricular activities",
        ],
    },
    {
        id: 3,
        icon: <Palette className="w-8 h-8" />,
        title: "Arts & Sciences",
        category: "Liberal Arts",
        description:
            "Liberal arts education fostering critical thinking and creative problem-solving. Our interdisciplinary approach encourages students to explore diverse fields of knowledge while developing strong analytical and communication skills. From literature and philosophy to natural sciences, students gain a well-rounded foundation for lifelong learning.",
        shortDescription:
            "Liberal arts education fostering critical thinking and creative problem-solving",
        courses: "25+ Programs",
        color: "from-primary-dark to-accent-dark",
        image: "/images/landing/arts.svg",
        duration: "4 Years",
        students: "750+",
        degree: "Bachelor/Master",
        mode: "On Campus",
        curriculum: [
            "Critical Thinking & Philosophy",
            "Literature & Creative Writing",
            "History & Cultural Studies",
            "Natural Sciences & Research Methods",
            "Foreign Languages & Linguistics",
            "Art History & Visual Arts",
            "Psychology & Social Sciences",
            "Mathematics & Statistics",
        ],
        careers: [
            "Research Analyst",
            "Content Creator",
            "Museum Curator",
            "Social Worker",
            "Journalist",
            "Teacher/Professor",
            "Policy Analyst",
            "Cultural Consultant",
        ],
        requirements: [
            "High school diploma with diverse academic subjects",
            "Minimum GPA of 2.5 or equivalent",
            "Writing sample or portfolio",
            "Personal essay demonstrating intellectual curiosity",
            "Interview with academic advisor",
        ],
    },
    {
        id: 4,
        icon: <Stethoscope className="w-8 h-8" />,
        title: "Health Sciences",
        category: "Medical Programs",
        description:
            "Preparing the next generation of healthcare professionals and researchers. Our programs combine rigorous scientific training with compassionate patient care, utilizing state-of-the-art simulation labs and clinical partnerships. Students develop both technical expertise and the interpersonal skills essential for healthcare excellence.",
        shortDescription:
            "Preparing the next generation of healthcare professionals and researchers",
        courses: "20+ Programs",
        color: "from-accent to-accent-light",
        image: "/images/landing/health.svg",
        duration: "4-6 Years",
        students: "600+",
        degree: "Bachelor/Master/Doctorate",
        mode: "On Campus & Clinical",
        curriculum: [
            "Human Anatomy & Physiology",
            "Medical Terminology & Ethics",
            "Pharmacology & Drug Interactions",
            "Clinical Assessment & Diagnosis",
            "Patient Care & Communication",
            "Medical Research Methods",
            "Healthcare Technology Systems",
            "Public Health & Epidemiology",
        ],
        careers: [
            "Registered Nurse",
            "Physical Therapist",
            "Medical Technologist",
            "Healthcare Administrator",
            "Clinical Researcher",
            "Pharmacist",
            "Radiologic Technologist",
            "Health Educator",
        ],
        requirements: [
            "High school diploma with strong science and mathematics background",
            "Minimum GPA of 3.2 or equivalent",
            "Prerequisite courses in biology, chemistry, and physics",
            "Healthcare experience or volunteer work preferred",
            "Background check and immunization records",
        ],
    },
    {
        id: 5,
        icon: <School className="w-8 h-8" />,
        title: "Education",
        category: "Teaching Programs",
        description:
            "Innovative teacher preparation and educational leadership programs. Our education programs emphasize modern pedagogical approaches, inclusive teaching strategies, and technology integration. Students learn to inspire and educate diverse learners while developing skills in curriculum design and educational assessment.",
        shortDescription:
            "Innovative teacher preparation and educational leadership programs",
        courses: "15+ Programs",
        color: "from-primary to-accent",
        image: "/images/landing/education.svg",
        duration: "4 Years",
        students: "400+",
        degree: "Bachelor/Master",
        mode: "On Campus & Field Experience",
        curriculum: [
            "Educational Psychology & Development",
            "Curriculum Design & Assessment",
            "Classroom Management Strategies",
            "Inclusive Education & Special Needs",
            "Educational Technology Integration",
            "Teaching Methods & Pedagogy",
            "Educational Research & Data Analysis",
            "School Leadership & Administration",
        ],
        careers: [
            "Elementary Teacher",
            "Secondary Teacher",
            "Special Education Teacher",
            "School Counselor",
            "Educational Administrator",
            "Curriculum Specialist",
            "Educational Technology Coordinator",
            "Training & Development Specialist",
        ],
        requirements: [
            "High school diploma with strong academic performance",
            "Minimum GPA of 2.75 or equivalent",
            "Communication and interpersonal skills assessment",
            "Field experience or volunteer work with children/youth",
            "Background check and fingerprinting required",
        ],
    },
    {
        id: 6,
        icon: <BookMarked className="w-8 h-8" />,
        title: "Graduate Studies",
        category: "Advanced Programs",
        description:
            "Advanced degrees and research opportunities across all disciplines. Our graduate programs offer specialized knowledge and research experience under the mentorship of distinguished faculty. Students engage in cutting-edge research while developing expertise that advances their fields and prepares them for leadership roles.",
        shortDescription:
            "Advanced degrees and research opportunities across all disciplines",
        courses: "60+ Programs",
        color: "from-accent-dark to-primary",
        image: "/images/landing/graduate.svg",
        duration: "2-7 Years",
        students: "800+",
        degree: "Master/Doctorate",
        mode: "On Campus & Research",
        curriculum: [
            "Advanced Research Methodologies",
            "Specialized Subject Matter Expertise",
            "Statistical Analysis & Data Interpretation",
            "Academic Writing & Publication",
            "Grant Writing & Funding Acquisition",
            "Conference Presentation Skills",
            "Interdisciplinary Collaboration",
            "Ethics in Research & Practice",
        ],
        careers: [
            "Research Scientist",
            "University Professor",
            "Industry Specialist",
            "Policy Researcher",
            "Consultant",
            "R&D Manager",
            "Think Tank Analyst",
            "Academic Administrator",
        ],
        requirements: [
            "Bachelor's degree from accredited institution",
            "Minimum GPA of 3.0 in undergraduate studies",
            "GRE/GMAT scores (program dependent)",
            "Statement of purpose and research interests",
            "Three letters of recommendation from academic or professional references",
            "Research experience or relevant work experience preferred",
        ],
    },
];

export const features = [
    {
        icon: <Lightbulb className="w-8 h-8" />,
        title: "Innovation Hub",
        description:
            "State-of-the-art research facilities and startup incubators fostering breakthrough discoveries",
        color: "from-accent-light to-accent",
    },
    {
        icon: <Globe className="w-8 h-8" />,
        title: "Global Partnerships",
        description:
            "Collaborations with leading universities and institutions worldwide for impactful research",
        color: "from-primary to-primary-dark",
    },
    {
        icon: <Target className="w-8 h-8" />,
        title: "Career Success",
        description:
            "Comprehensive career services and industry connections ensuring graduate success",
        color: "from-accent-dark to-primary",
    },
];

export const facilities = [
    {
        id: 1,
        name: "Grand Auditorium",
        subtitle: "Where Ideas Take Center Stage",
        description:
            "Perfectly crafted for unforgettable moments, from inspiring talks to milestone gatherings in a setting that speaks prestige.",
        capacity: "500 guests",
        icon: Mic,
        position: { top: "18%", left: "17%" },
        gallery: [
            "/images/landing/assets/grand-auditorium.jpg",
            "/images/landing/assets/grand-auditorium.jpg",
            "/images/landing/assets/grand-auditorium.jpg",
            "/images/landing/assets/grand-auditorium.jpg",
        ],
        features: [
            "Premium Sound System",
            "Theatrical Lighting",
            "HD Recording",
        ],
        atmosphere: "Inspiring & Professional",
        stats: { events: "200+", satisfaction: "98%" },
    },
    {
        id: 2,
        name: "Innovation Hub",
        subtitle: "Where Tomorrow's Solutions Begin",
        description:
            "A creative space designed for minds that dream big, build, collaborate, and grow ideas into reality.",
        capacity: "100 guests",
        icon: Lightbulb,
        position: { top: "12%", right: "17%" },
        gallery: [
            "/images/landing/assets/innovation-hub.jpg",
            "/images/landing/assets/innovation-hub.jpg",
            "/images/landing/assets/innovation-hub.jpg",
            "/images/landing/assets/innovation-hub.jpg",
        ],
        features: [
            "Smart Collaboration Tools",
            "Flexible Configurations",
            "Rapid Prototyping",
        ],
        atmosphere: "Creative & Dynamic",
        stats: { projects: "500+", startups: "50+" },
    },
    {
        id: 3,
        name: "Sky Lounge",
        subtitle: "Elevating Campus Connections",
        description:
            "Panoramic views meet elegant ambiance, ideal for meaningful conversations and celebratory moments.",
        capacity: "150 guests",
        icon: Wine,
        position: { bottom: "50%", left: "13%" },
        gallery: [
            "/images/landing/assets/sky-lounge.jpg",
            "/images/landing/assets/sky-lounge.jpg",
            "/images/landing/assets/sky-lounge.jpg",
            "/images/landing/assets/sky-lounge.jpg",
        ],
        features: ["360° City Views", "Ambient Atmosphere", "Premium Catering"],
        atmosphere: "Elegant & Relaxed",
        stats: { events: "150+", rating: "4.9/5" },
    },
    {
        id: 4,
        name: "Library & Study Spaces",
        subtitle: "Knowledge Sanctuary",
        description:
            "Quiet spaces designed for deep focus and collaborative learning in a modern academic environment.",
        capacity: "200 guests",
        icon: Library,
        position: { bottom: "40%", left: "45%" },
        gallery: [
            "/images/landing/assets/library.jpg",
            "/images/landing/assets/library.jpg",
            "/images/landing/assets/library.jpg",
            "/images/landing/assets/library.jpg",
        ],
        features: [
            "Silent Study Areas",
            "Group Discussion Rooms",
            "Digital Resources",
        ],
        atmosphere: "Peaceful & Focused",
        stats: { visitors: "1000+", resources: "50k+" },
    },
    {
        id: 5,
        name: "Health Center",
        subtitle: "Your Campus Care Partner",
        description:
            "On-campus health services for students and staff, offering first aid, medical consultations, and wellness support.",
        capacity: "Open Daily",
        icon: HeartPulse,
        position: { bottom: "35%", right: "18%" },
        gallery: [
            "/images/landing/assets/health-center.jpg",
            "/images/landing/assets/health-center.jpg",
            "/images/landing/assets/health-center.jpg",
            "/images/landing/assets/health-center.jpg",
        ],
        features: [
            "First Aid Services",
            "Doctor Consultations",
            "Wellness Programs",
        ],
        atmosphere: "Clean & Caring",
        stats: { patients: "800+/year", rating: "4.8/5" },
    },
];

export const faqs = [
    {
        question: "What are the admission requirements for LOD University?",
        answer: "Admission requirements vary by program, but generally include a completed application, official transcripts, standardized test scores (SAT/ACT), letters of recommendation, and a personal statement. International students may need TOEFL/IELTS scores. Specific requirements for each program can be found on our admissions website.",
    },
    {
        question: "What financial aid options are available?",
        answer: "LOD University offers comprehensive financial aid including merit-based scholarships, need-based grants, work-study programs, and federal student loans. Over 85% of our students receive some form of financial assistance. We also offer payment plans and emergency financial aid for unexpected circumstances.",
    },
    {
        question: "Can I change my major after enrollment?",
        answer: "Yes! We encourage academic exploration. Students can change majors within their first two years without penalty. Our academic advisors work closely with students to ensure a smooth transition and help create a graduation plan that fits their new academic goals.",
    },
    {
        question: "What support services are available for students?",
        answer: "LOD University provides comprehensive support including academic tutoring, career counseling, mental health services, disability support, international student services, and 24/7 campus security. We also offer study abroad programs, internship placement, and alumni networking opportunities.",
    },
    {
        question: "What is campus housing like?",
        answer: "Our campus features modern residence halls with various living options from traditional dorms to apartment-style housing. All rooms include high-speed internet, study areas, and common spaces. First-year students are guaranteed on-campus housing, and upperclassmen can choose from on-campus or nearby off-campus options.",
    },
    {
        question: "How do I schedule a campus visit?",
        answer: "Campus visits can be scheduled through our admissions website or by calling our admissions office. We offer guided tours, information sessions, overnight stays, and virtual tours. Group visits for schools and organizations can also be arranged with advance notice.",
    },
    {
        question: "Can campus facilities be rented?",
        answer: "Yes, LOD University offers facility rentals for events such as conferences, workshops, and community gatherings. Availability and rates vary by venue. Interested parties can contact our Events Office or visit the Facility Rental section on our website for more details and booking procedures.",
    },
];
